groups:
 - name: "v1"
   channels:
    - name: alpha
      version: v1.2.23+fix50
    - name: beta
      version: v1.2.23+fix25
    - name: ea
      version: v1.1.22+fix40
    - name: stable
      version: v1.1.21+fix40
    - name: rock-solid
      version: v1.1.21
